<?php

return [
    'canonical_fields' => [
        [
            'key' => 'external_id',
            'field_group' => 'identity',
            'label' => 'External product ID',
            'description' => 'Stable product identifier from the affiliate network or merchant feed.',
            'data_type' => 'string',
            'target_column' => 'provider_product_id',
            'is_required' => true,
            'sort_order' => 10,
        ],
        [
            'key' => 'sku',
            'field_group' => 'identity',
            'label' => 'SKU',
            'description' => 'Merchant stock keeping unit.',
            'data_type' => 'string',
            'target_column' => 'sku',
            'sort_order' => 20,
        ],
        [
            'key' => 'gtin',
            'field_group' => 'identity',
            'label' => 'GTIN/EAN',
            'description' => 'GTIN, EAN, UPC, or ISBN product identifier.',
            'data_type' => 'string',
            'target_column' => 'ean',
            'is_filterable' => true,
            'sort_order' => 30,
        ],
        [
            'key' => 'mpn',
            'field_group' => 'identity',
            'label' => 'MPN',
            'description' => 'Manufacturer part number.',
            'data_type' => 'string',
            'target_column' => 'mpn',
            'sort_order' => 40,
        ],
        [
            'key' => 'brand',
            'field_group' => 'identity',
            'label' => 'Brand',
            'description' => 'Product brand or manufacturer.',
            'data_type' => 'string',
            'target_column' => 'brand',
            'is_searchable' => true,
            'is_filterable' => true,
            'sort_order' => 50,
        ],
        [
            'key' => 'item_group_id',
            'field_group' => 'identity',
            'label' => 'Item group ID',
            'description' => 'Shared identifier for product variants.',
            'data_type' => 'string',
            'target_column' => 'item_group_id',
            'is_variant' => true,
            'sort_order' => 60,
        ],
        [
            'key' => 'network_campaign_id',
            'field_group' => 'identity',
            'label' => 'Network campaign ID',
            'description' => 'Affiliate-network campaign or advertiser identifier supplied by the feed.',
            'data_type' => 'string',
            'metadata_path' => 'network.campaign_id',
            'sort_order' => 70,
        ],
        [
            'key' => 'network_merchant_id',
            'field_group' => 'identity',
            'label' => 'Network merchant ID',
            'description' => 'Affiliate-network merchant or advertiser identifier supplied by the feed.',
            'data_type' => 'string',
            'metadata_path' => 'network.merchant_id',
            'sort_order' => 80,
        ],
        [
            'key' => 'network_merchant_name',
            'field_group' => 'identity',
            'label' => 'Network merchant name',
            'description' => 'Affiliate-network merchant or advertiser name supplied by the feed.',
            'data_type' => 'string',
            'metadata_path' => 'network.merchant_name',
            'sort_order' => 90,
        ],
        [
            'key' => 'network_feed_id',
            'field_group' => 'identity',
            'label' => 'Network feed ID',
            'description' => 'Affiliate-network feed identifier supplied by the feed.',
            'data_type' => 'string',
            'metadata_path' => 'network.feed_id',
            'sort_order' => 95,
        ],
        [
            'key' => 'title',
            'field_group' => 'content',
            'label' => 'Title',
            'description' => 'Public product title.',
            'data_type' => 'string',
            'target_column' => 'title',
            'is_required' => true,
            'is_searchable' => true,
            'sort_order' => 100,
        ],
        [
            'key' => 'description',
            'field_group' => 'content',
            'label' => 'Description',
            'description' => 'Public product description.',
            'data_type' => 'text',
            'target_column' => 'description',
            'is_searchable' => true,
            'sort_order' => 110,
        ],
        [
            'key' => 'category_path',
            'field_group' => 'content',
            'label' => 'Category path',
            'description' => 'Source category path before mapping to a site category.',
            'data_type' => 'string',
            'metadata_path' => 'category.path',
            'sort_order' => 120,
        ],
        [
            'key' => 'network_category_id',
            'field_group' => 'content',
            'label' => 'Network category ID',
            'description' => 'Affiliate-network category identifier supplied by the feed.',
            'data_type' => 'string',
            'metadata_path' => 'category.network_id',
            'sort_order' => 125,
        ],
        [
            'key' => 'network_category_name',
            'field_group' => 'content',
            'label' => 'Network category name',
            'description' => 'Affiliate-network category label supplied by the feed.',
            'data_type' => 'string',
            'metadata_path' => 'category.network_name',
            'sort_order' => 126,
        ],
        [
            'key' => 'merchant_category',
            'field_group' => 'content',
            'label' => 'Merchant category',
            'description' => 'Category label supplied by the merchant or network.',
            'data_type' => 'string',
            'target_column' => 'merchant_category',
            'is_filterable' => true,
            'sort_order' => 130,
        ],
        [
            'key' => 'product_type',
            'field_group' => 'content',
            'label' => 'Product type',
            'description' => 'Normalized product type used for browsing and filtering.',
            'data_type' => 'string',
            'target_column' => 'product_type',
            'is_filterable' => true,
            'sort_order' => 140,
        ],
        [
            'key' => 'short_description',
            'field_group' => 'content',
            'label' => 'Short description',
            'description' => 'Short product description supplied by the feed.',
            'data_type' => 'text',
            'metadata_path' => 'content.short_description',
            'is_searchable' => true,
            'sort_order' => 150,
        ],
        [
            'key' => 'keywords',
            'field_group' => 'content',
            'label' => 'Keywords',
            'description' => 'Product keywords supplied by the feed.',
            'data_type' => 'string',
            'metadata_path' => 'content.keywords',
            'is_searchable' => true,
            'sort_order' => 160,
        ],
        [
            'key' => 'promotional_text',
            'field_group' => 'content',
            'label' => 'Promotional text',
            'description' => 'Promotional product text supplied by the feed.',
            'data_type' => 'text',
            'metadata_path' => 'content.promotional_text',
            'sort_order' => 170,
        ],
        [
            'key' => 'merchant_url',
            'field_group' => 'urls',
            'label' => 'Merchant URL',
            'description' => 'Original product page URL at the merchant.',
            'data_type' => 'url',
            'target_column' => 'product_url',
            'sort_order' => 200,
        ],
        [
            'key' => 'affiliate_url',
            'field_group' => 'urls',
            'label' => 'Affiliate URL',
            'description' => 'Outbound URL used for click tracking and commission attribution.',
            'data_type' => 'url',
            'target_column' => 'affiliate_url',
            'is_required' => true,
            'sort_order' => 210,
        ],
        [
            'key' => 'tracking_url',
            'field_group' => 'urls',
            'label' => 'Tracking URL',
            'description' => 'Optional network tracking URL when distinct from the affiliate URL.',
            'data_type' => 'url',
            'target_column' => 'tracking_url',
            'sort_order' => 220,
        ],
        [
            'key' => 'image_url',
            'field_group' => 'urls',
            'label' => 'Image URL',
            'description' => 'Primary product image URL.',
            'data_type' => 'url',
            'target_column' => 'image_url',
            'sort_order' => 230,
        ],
        [
            'key' => 'additional_image_urls',
            'field_group' => 'urls',
            'label' => 'Additional image URLs',
            'description' => 'Additional product image URLs.',
            'data_type' => 'array',
            'target_column' => 'additional_image_urls',
            'sort_order' => 240,
        ],
        [
            'key' => 'network_image_url',
            'field_group' => 'urls',
            'label' => 'Network image URL',
            'description' => 'Network-hosted or transformed product image URL.',
            'data_type' => 'url',
            'metadata_path' => 'images.network_url',
            'sort_order' => 250,
        ],
        [
            'key' => 'price',
            'field_group' => 'pricing',
            'label' => 'Price',
            'description' => 'Current public product price.',
            'data_type' => 'decimal',
            'target_column' => 'price',
            'is_required' => true,
            'sort_order' => 300,
        ],
        [
            'key' => 'old_price',
            'field_group' => 'pricing',
            'label' => 'Old price',
            'description' => 'Previous price, RRP, or before-discount price.',
            'data_type' => 'decimal',
            'target_column' => 'old_price',
            'sort_order' => 310,
        ],
        [
            'key' => 'currency',
            'field_group' => 'pricing',
            'label' => 'Currency',
            'description' => 'ISO 4217 currency code.',
            'data_type' => 'string',
            'target_column' => 'currency',
            'sort_order' => 320,
        ],
        [
            'key' => 'shipping_cost',
            'field_group' => 'pricing',
            'label' => 'Shipping cost',
            'description' => 'Current shipping cost for the product.',
            'data_type' => 'decimal',
            'target_column' => 'shipping_cost',
            'sort_order' => 330,
        ],
        [
            'key' => 'store_price',
            'field_group' => 'pricing',
            'label' => 'Store price',
            'description' => 'Store price supplied by the merchant or network feed.',
            'data_type' => 'decimal',
            'metadata_path' => 'pricing.store_price',
            'sort_order' => 340,
        ],
        [
            'key' => 'display_price',
            'field_group' => 'pricing',
            'label' => 'Display price',
            'description' => 'Human-readable price string supplied by the feed.',
            'data_type' => 'string',
            'metadata_path' => 'pricing.display_price',
            'sort_order' => 350,
        ],
        [
            'key' => 'availability',
            'field_group' => 'availability',
            'label' => 'Availability',
            'description' => 'Normalized stock status such as in_stock, out_of_stock, preorder, or backorder.',
            'data_type' => 'string',
            'target_column' => 'availability',
            'is_filterable' => true,
            'sort_order' => 400,
        ],
        [
            'key' => 'stock_quantity',
            'field_group' => 'availability',
            'label' => 'Stock quantity',
            'description' => 'Available stock quantity if supplied by the feed.',
            'data_type' => 'integer',
            'target_column' => 'stock_quantity',
            'sort_order' => 410,
        ],
        [
            'key' => 'delivery_time',
            'field_group' => 'availability',
            'label' => 'Delivery time',
            'description' => 'Human readable delivery promise from the merchant.',
            'data_type' => 'string',
            'target_column' => 'delivery_time',
            'sort_order' => 420,
        ],
        [
            'key' => 'condition',
            'field_group' => 'availability',
            'label' => 'Condition',
            'description' => 'Product condition, usually new, used, or refurbished.',
            'data_type' => 'string',
            'target_column' => 'condition',
            'sort_order' => 430,
        ],
        [
            'key' => 'availability_date',
            'field_group' => 'availability',
            'label' => 'Availability date',
            'description' => 'Expected availability date or availability note from the merchant feed.',
            'data_type' => 'string',
            'metadata_path' => 'availability.date',
            'sort_order' => 440,
        ],
        [
            'key' => 'color',
            'field_group' => 'variants',
            'label' => 'Color',
            'description' => 'Variant color.',
            'data_type' => 'string',
            'target_column' => 'color',
            'is_filterable' => true,
            'is_variant' => true,
            'sort_order' => 500,
        ],
        [
            'key' => 'size',
            'field_group' => 'variants',
            'label' => 'Size',
            'description' => 'Variant size.',
            'data_type' => 'string',
            'target_column' => 'size',
            'is_filterable' => true,
            'is_variant' => true,
            'sort_order' => 510,
        ],
        [
            'key' => 'gender',
            'field_group' => 'variants',
            'label' => 'Gender',
            'description' => 'Audience or fit gender.',
            'data_type' => 'string',
            'target_column' => 'gender',
            'is_filterable' => true,
            'is_variant' => true,
            'sort_order' => 520,
        ],
        [
            'key' => 'material',
            'field_group' => 'variants',
            'label' => 'Material',
            'description' => 'Product material.',
            'data_type' => 'string',
            'target_column' => 'material',
            'is_filterable' => true,
            'is_variant' => true,
            'sort_order' => 530,
        ],
        [
            'key' => 'pattern',
            'field_group' => 'variants',
            'label' => 'Pattern',
            'description' => 'Product pattern or print.',
            'data_type' => 'string',
            'target_column' => 'pattern',
            'is_filterable' => true,
            'is_variant' => true,
            'sort_order' => 540,
        ],
        [
            'key' => 'age_group',
            'field_group' => 'variants',
            'label' => 'Age group',
            'description' => 'Audience age group.',
            'data_type' => 'string',
            'target_column' => 'age_group',
            'is_filterable' => true,
            'is_variant' => true,
            'sort_order' => 550,
        ],
        [
            'key' => 'weight',
            'field_group' => 'specifications',
            'label' => 'Weight',
            'description' => 'Product weight as supplied by the merchant feed.',
            'data_type' => 'string',
            'metadata_path' => 'specifications.weight',
            'sort_order' => 560,
        ],
        [
            'key' => 'brand_id',
            'field_group' => 'specifications',
            'label' => 'Brand ID',
            'description' => 'Brand identifier supplied by the merchant or network feed.',
            'data_type' => 'string',
            'metadata_path' => 'brand.id',
            'sort_order' => 570,
        ],
        [
            'key' => 'specifications',
            'field_group' => 'specifications',
            'label' => 'Specifications',
            'description' => 'Raw product specifications supplied by the feed.',
            'data_type' => 'text',
            'metadata_path' => 'specifications.raw',
            'is_searchable' => true,
            'sort_order' => 580,
        ],
        [
            'key' => 'product_model',
            'field_group' => 'specifications',
            'label' => 'Product model',
            'description' => 'Product model supplied by the feed.',
            'data_type' => 'string',
            'metadata_path' => 'specifications.product_model',
            'is_searchable' => true,
            'sort_order' => 590,
        ],
        [
            'key' => 'model_number',
            'field_group' => 'specifications',
            'label' => 'Model number',
            'description' => 'Model number supplied by the feed.',
            'data_type' => 'string',
            'metadata_path' => 'specifications.model_number',
            'is_searchable' => true,
            'sort_order' => 595,
        ],
        [
            'key' => 'dimensions',
            'field_group' => 'specifications',
            'label' => 'Dimensions',
            'description' => 'Product dimensions supplied by the feed.',
            'data_type' => 'string',
            'metadata_path' => 'specifications.dimensions',
            'sort_order' => 596,
        ],
        [
            'key' => 'google_product_category',
            'field_group' => 'classification',
            'label' => 'Google product category',
            'description' => 'Google taxonomy category when supplied by a feed.',
            'data_type' => 'string',
            'metadata_path' => 'classification.google_product_category',
            'sort_order' => 600,
        ],
        [
            'key' => 'energy_label',
            'field_group' => 'compliance',
            'label' => 'Energy label',
            'description' => 'Energy efficiency label or class.',
            'data_type' => 'string',
            'metadata_path' => 'compliance.energy_label',
            'sort_order' => 700,
        ],
        [
            'key' => 'adult',
            'field_group' => 'compliance',
            'label' => 'Adult',
            'description' => 'Whether the product is adult-oriented.',
            'data_type' => 'boolean',
            'metadata_path' => 'compliance.adult',
            'sort_order' => 710,
        ],
        [
            'key' => 'feed_language',
            'field_group' => 'feed',
            'label' => 'Feed language',
            'description' => 'Language code supplied by the source feed.',
            'data_type' => 'string',
            'metadata_path' => 'feed.language',
            'sort_order' => 800,
        ],
        [
            'key' => 'source_last_updated_at',
            'field_group' => 'feed',
            'label' => 'Source last updated at',
            'description' => 'Last-updated timestamp supplied by the source feed.',
            'data_type' => 'string',
            'metadata_path' => 'feed.last_updated_at',
            'sort_order' => 810,
        ],
    ],

    'provider_templates' => [
        [
            'name' => 'Awin legacy product feed',
            'slug' => 'awin-legacy',
            'provider' => 'awin',
            'source_format' => 'csv',
            'delimiter' => ',',
            'decimal_separator' => '.',
            'thousands_separator' => ',',
            'currency' => 'EUR',
            'mappings' => [
                'external_id' => ['source_field' => 'aw_product_id', 'fallback_fields' => ['merchant_product_id']],
                'sku' => ['source_field' => 'merchant_product_id'],
                'network_merchant_id' => ['source_field' => 'merchant_id'],
                'network_merchant_name' => ['source_field' => 'merchant_name'],
                'network_feed_id' => ['source_field' => 'data_feed_id'],
                'title' => ['source_field' => 'product_name'],
                'description' => ['source_field' => 'description'],
                'category_path' => ['source_field' => 'merchant_product_category_path', 'fallback_fields' => ['merchant_category', 'category_name']],
                'network_category_id' => ['source_field' => 'category_id'],
                'network_category_name' => ['source_field' => 'category_name'],
                'merchant_category' => ['source_field' => 'merchant_category', 'fallback_fields' => ['category_name']],
                'product_type' => ['source_field' => 'product_type', 'fallback_fields' => ['category_name']],
                'short_description' => ['source_field' => 'product_short_description'],
                'keywords' => ['source_field' => 'keywords'],
                'promotional_text' => ['source_field' => 'promotional_text'],
                'merchant_url' => ['source_field' => 'merchant_deep_link'],
                'affiliate_url' => ['source_field' => 'aw_deep_link'],
                'image_url' => ['source_field' => 'merchant_image_url', 'fallback_fields' => ['aw_image_url']],
                'network_image_url' => ['source_field' => 'aw_image_url'],
                'price' => ['source_field' => 'search_price', 'transform_type' => 'money'],
                'old_price' => ['source_field' => 'rrp_price', 'transform_type' => 'money'],
                'currency' => ['source_field' => 'currency'],
                'shipping_cost' => ['source_field' => 'delivery_cost', 'transform_type' => 'money'],
                'store_price' => ['source_field' => 'store_price', 'transform_type' => 'money'],
                'display_price' => ['source_field' => 'display_price'],
                'availability' => ['source_field' => 'in_stock', 'transform_type' => 'availability'],
                'stock_quantity' => ['source_field' => 'stock_quantity', 'transform_type' => 'integer'],
                'condition' => ['source_field' => 'condition'],
                'brand' => ['source_field' => 'brand_name'],
                'brand_id' => ['source_field' => 'brand_id'],
                'gtin' => ['source_field' => 'product_GTIN', 'fallback_fields' => ['ean', 'upc', 'isbn']],
                'mpn' => ['source_field' => 'mpn', 'fallback_fields' => ['model_number']],
                'color' => ['source_field' => 'colour'],
                'specifications' => ['source_field' => 'specifications'],
                'product_model' => ['source_field' => 'product_model'],
                'model_number' => ['source_field' => 'model_number'],
                'dimensions' => ['source_field' => 'dimensions'],
                'feed_language' => ['source_field' => 'language'],
                'source_last_updated_at' => ['source_field' => 'last_updated'],
            ],
        ],
        [
            'name' => 'Daisycon standard product feed',
            'slug' => 'daisycon-standard',
            'provider' => 'daisycon',
            'source_format' => 'csv',
            'delimiter' => ',',
            'decimal_separator' => '.',
            'thousands_separator' => ',',
            'currency' => 'EUR',
            'mappings' => [
                'external_id' => ['source_field' => 'sku', 'fallback_fields' => ['id', 'product_id']],
                'sku' => ['source_field' => 'sku'],
                'title' => ['source_field' => 'title', 'fallback_fields' => ['name']],
                'description' => ['source_field' => 'description'],
                'category_path' => ['source_field' => 'category'],
                'merchant_category' => ['source_field' => 'category'],
                'merchant_url' => ['source_field' => 'link'],
                'affiliate_url' => ['source_field' => 'link'],
                'image_url' => ['source_field' => 'image', 'fallback_fields' => ['image_link']],
                'price' => ['source_field' => 'price', 'transform_type' => 'money'],
                'old_price' => ['source_field' => 'old_price', 'fallback_fields' => ['original_price'], 'transform_type' => 'money'],
                'currency' => ['source_field' => 'currency'],
                'shipping_cost' => ['source_field' => 'delivery_cost', 'fallback_fields' => ['shipping_cost'], 'transform_type' => 'money'],
                'availability' => ['source_field' => 'in_stock', 'fallback_fields' => ['availability'], 'transform_type' => 'availability'],
                'delivery_time' => ['source_field' => 'delivery_time'],
                'brand' => ['source_field' => 'brand'],
                'gtin' => ['source_field' => 'ean', 'fallback_fields' => ['gtin']],
            ],
        ],
        [
            'name' => 'TradeTracker standard product feed',
            'slug' => 'tradetracker-standard',
            'provider' => 'tradetracker',
            'source_format' => 'csv',
            'delimiter' => ',',
            'decimal_separator' => '.',
            'thousands_separator' => ',',
            'currency' => 'EUR',
            'mappings' => [
                'external_id' => ['source_field' => 'ID', 'fallback_fields' => ['product ID', 'productID', 'uniqueID']],
                'sku' => ['source_field' => 'SKU', 'fallback_fields' => ['productID', 'uniqueID', 'product ID', 'ID', 'number']],
                'network_campaign_id' => ['source_field' => 'campaignID'],
                'title' => ['source_field' => 'Name'],
                'description' => ['source_field' => 'Description'],
                'category_path' => ['source_field' => 'Category', 'fallback_fields' => ['categoryPath', 'categories']],
                'merchant_category' => ['source_field' => 'Category', 'fallback_fields' => ['categoryPath', 'categories', 'SubCategory']],
                'product_type' => ['source_field' => 'type'],
                'merchant_url' => ['source_field' => 'ProductURL', 'fallback_fields' => ['productURL']],
                'affiliate_url' => ['source_field' => 'ProductURL', 'fallback_fields' => ['productURL']],
                'tracking_url' => ['source_field' => 'ProductURL', 'fallback_fields' => ['productURL']],
                'image_url' => ['source_field' => 'ImageURL', 'fallback_fields' => ['imageURL']],
                'price' => ['source_field' => 'Price', 'transform_type' => 'money'],
                'old_price' => ['source_field' => 'FromPrice', 'fallback_fields' => ['OldPrice'], 'transform_type' => 'money'],
                'currency' => ['source_field' => 'Currency'],
                'shipping_cost' => ['source_field' => 'ShippingCosts', 'fallback_fields' => ['deliveryCosts'], 'transform_type' => 'money'],
                'availability' => ['source_field' => 'Availability', 'fallback_fields' => ['stock'], 'transform_type' => 'stock_availability'],
                'stock_quantity' => ['source_field' => 'stock', 'transform_type' => 'integer'],
                'delivery_time' => ['source_field' => 'DeliveryTime'],
                'brand' => ['source_field' => 'Brand'],
                'gtin' => ['source_field' => 'EAN'],
                'mpn' => ['source_field' => 'MPN', 'fallback_fields' => ['number']],
                'weight' => ['source_field' => 'weight'],
            ],
        ],
        [
            'name' => 'TradeTracker JSON product feed',
            'slug' => 'tradetracker-json',
            'provider' => 'tradetracker',
            'source_format' => 'json',
            'row_selector' => 'products',
            'decimal_separator' => '.',
            'thousands_separator' => ',',
            'currency' => 'EUR',
            'mappings' => [
                'external_id' => ['source_field' => 'ID'],
                'network_campaign_id' => ['source_field' => 'campaignID'],
                'title' => ['source_field' => 'name'],
                'description' => ['source_field' => 'description'],
                'category_path' => ['source_field' => 'categories', 'transform_type' => 'first_value'],
                'merchant_category' => ['source_field' => 'categories', 'transform_type' => 'first_value'],
                'product_type' => ['source_field' => 'categories', 'transform_type' => 'first_value'],
                'affiliate_url' => ['source_field' => 'URL'],
                'tracking_url' => ['source_field' => 'URL'],
                'image_url' => ['source_field' => 'images.0'],
                'additional_image_urls' => ['source_field' => 'images', 'transform_type' => 'array'],
                'price' => ['source_field' => 'price.amount', 'transform_type' => 'money'],
                'old_price' => ['source_field' => 'properties.Adviesprijs.0', 'transform_type' => 'money'],
                'currency' => ['source_field' => 'price.currency'],
                'shipping_cost' => ['source_field' => 'properties.deliveryCosts.0', 'transform_type' => 'money'],
                'availability' => ['source_field' => 'properties.availability.0', 'transform_type' => 'availability'],
                'availability_date' => ['source_field' => 'properties.availability_date.0'],
                'delivery_time' => ['source_field' => 'properties.deliveryTime.0'],
                'condition' => ['source_field' => 'properties.condition.0'],
                'brand' => ['source_field' => 'properties.brand.0'],
                'gtin' => ['source_field' => 'properties.GTIN.0'],
                'mpn' => ['source_field' => 'properties.MPN.0'],
                'weight' => ['source_field' => 'properties.weight.0'],
            ],
        ],
        [
            'name' => 'TradeTracker XML product feed',
            'slug' => 'tradetracker-xml',
            'provider' => 'tradetracker',
            'source_format' => 'xml',
            'row_selector' => 'product',
            'decimal_separator' => '.',
            'thousands_separator' => ',',
            'currency' => 'EUR',
            'mappings' => [
                'external_id' => ['source_field' => '@attributes.ID'],
                'network_campaign_id' => ['source_field' => 'campaignID'],
                'title' => ['source_field' => 'name'],
                'description' => ['source_field' => 'description'],
                'category_path' => ['source_field' => 'properties.property[name=categoryPath].value', 'transform_type' => 'first_value'],
                'merchant_category' => ['source_field' => 'properties.property[name=categoryPath].value', 'transform_type' => 'first_value'],
                'product_type' => ['source_field' => 'properties.property[name=type].value'],
                'affiliate_url' => ['source_field' => 'URL'],
                'tracking_url' => ['source_field' => 'URL'],
                'image_url' => ['source_field' => 'images.image', 'transform_type' => 'first_value'],
                'additional_image_urls' => ['source_field' => 'images.image', 'transform_type' => 'array'],
                'price' => ['source_field' => 'price', 'transform_type' => 'money'],
                'old_price' => ['source_field' => 'properties.property[name=fromPrice].value', 'transform_type' => 'money'],
                'currency' => ['source_field' => 'price.@attributes.currency', 'default_value' => 'EUR'],
                'shipping_cost' => ['source_field' => 'properties.property[name=deliveryCosts].value', 'transform_type' => 'money'],
                'availability' => ['source_field' => 'properties.property[name=stock].value', 'transform_type' => 'stock_availability'],
                'stock_quantity' => ['source_field' => 'properties.property[name=stock].value', 'transform_type' => 'integer'],
                'delivery_time' => ['source_field' => 'properties.property[name=deliveryTime].value'],
                'brand' => ['source_field' => 'properties.property[name=brand].value'],
                'gtin' => ['source_field' => 'properties.property[name=EAN].value'],
                'mpn' => ['source_field' => 'properties.property[name=MPN].value'],
                'weight' => ['source_field' => 'properties.property[name=weight].value'],
            ],
        ],
        [
            'name' => 'Google Merchant style feed',
            'slug' => 'google-merchant',
            'provider' => 'custom',
            'source_format' => 'csv',
            'delimiter' => ',',
            'decimal_separator' => '.',
            'thousands_separator' => ',',
            'currency' => 'EUR',
            'mappings' => [
                'external_id' => ['source_field' => 'id'],
                'item_group_id' => ['source_field' => 'item_group_id'],
                'title' => ['source_field' => 'title'],
                'description' => ['source_field' => 'description'],
                'category_path' => ['source_field' => 'product_type'],
                'merchant_category' => ['source_field' => 'product_type'],
                'google_product_category' => ['source_field' => 'google_product_category'],
                'merchant_url' => ['source_field' => 'link'],
                'affiliate_url' => ['source_field' => 'ads_redirect', 'fallback_fields' => ['link']],
                'image_url' => ['source_field' => 'image_link'],
                'additional_image_urls' => ['source_field' => 'additional_image_link', 'transform_type' => 'array'],
                'price' => ['source_field' => 'sale_price', 'fallback_fields' => ['price'], 'transform_type' => 'money'],
                'old_price' => ['source_field' => 'price', 'transform_type' => 'money'],
                'currency' => ['source_field' => 'currency'],
                'availability' => ['source_field' => 'availability', 'transform_type' => 'availability'],
                'condition' => ['source_field' => 'condition'],
                'brand' => ['source_field' => 'brand'],
                'gtin' => ['source_field' => 'gtin'],
                'mpn' => ['source_field' => 'mpn'],
                'color' => ['source_field' => 'color'],
                'size' => ['source_field' => 'size'],
                'gender' => ['source_field' => 'gender'],
                'material' => ['source_field' => 'material'],
                'pattern' => ['source_field' => 'pattern'],
                'age_group' => ['source_field' => 'age_group'],
                'adult' => ['source_field' => 'adult', 'transform_type' => 'boolean'],
            ],
        ],
    ],
];
